#!/bin/bash
set -e

cat <<EOF > /etc/resolv.conf
# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 10.89.0.2
nameserver 8.8.8.8
nameserver 127.0.0.11
options ndots:0

# Based on host file: '/etc/resolv.conf' (internal resolver)
# ExtServers: [10.89.0.2]
# Overrides: [nameservers]
# Option ndots from: internal
EOF

echo "Custom /etc/resolv.conf applied."

exec "$@"
